[package]
name = "axum_app_test_git_pod"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
bs58 = "0.5.1"
serde = { version = "1.0.219", features = ["derive"] }

tokio = { version = "1.45.1", features = ["full"] }
tracing-subscriber = "0.3.19"
